# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(250, 250)
        MainWindow.setMinimumSize(QtCore.QSize(250, 250))
        MainWindow.setMaximumSize(QtCore.QSize(250, 250))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_option = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_option.setGeometry(QtCore.QRect(80, 110, 81, 20))
        self.input_option.setObjectName("input_option")
        self.button_submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_submit.setGeometry(QtCore.QRect(80, 140, 75, 23))
        self.button_submit.setObjectName("button_submit")
        self.label_menu = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_menu.setGeometry(QtCore.QRect(60, 20, 121, 21))
        self.label_menu.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_menu.setObjectName("label_menu")
        self.label_option_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_option_1.setGeometry(QtCore.QRect(100, 50, 41, 21))
        self.label_option_1.setObjectName("label_option_1")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-20, 30, 271, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label_display = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_display.setGeometry(QtCore.QRect(20, 180, 201, 20))
        self.label_display.setText("")
        self.label_display.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_display.setObjectName("label_display")
        self.label_input = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_input.setGeometry(QtCore.QRect(10, 110, 61, 16))
        self.label_input.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_input.setObjectName("label_input")
        self.label_option_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_option_2.setGeometry(QtCore.QRect(100, 80, 47, 13))
        self.label_option_2.setObjectName("label_option_2")
        self.line_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(-10, 10, 271, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ballot"))
        self.button_submit.setText(_translate("MainWindow", "SUBMIT"))
        self.label_menu.setText(_translate("MainWindow", "VOTE MENU"))
        self.label_option_1.setText(_translate("MainWindow", "v: Vote "))
        self.label_input.setText(_translate("MainWindow", "Option:"))
        self.label_option_2.setText(_translate("MainWindow", "x: Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
